PRODUCT_NAME = "HaloCue"
CHINESE_SUBTITLE = "AzureArchive 剧情演出工具"
ENGLISH_SUBTITLE = "Narrative Staging for AzureArchive"
VERSION = "0.9.3"
DISPLAY_NAME = "HaloCue 0.9.3"
APP_ID = "halocue-local-server-v1"
MIN_PYTHON = (3, 10)
PUBLIC_ARCHIVE_NAME = f"{PRODUCT_NAME}-{VERSION}-windows-x64.zip"
PRIVATE_ARCHIVE_NAME = f"{PRODUCT_NAME}-{VERSION}-private-windows-x64.zip"
